### ISSUE TITLE
update documentation/Readme

### ISSUE THREAD

**Issue by awmatheson** [Azure/aml-template#26]
Update the Documentation of all `aml-<actions>`

- [x] https://github.com/Azure/aml-run/
- [x] https://github.com/Azure/aml-compute/
- [x] https://github.com/Azure/aml-deploy/
- [x] https://github.com/Azure/aml-registermodel/
- [x] https://github.com/Azure/aml-workspace/
- [x] https://github.com/Azure/aml-template/

**Comment by awmatheson** [comment]
- [ ] Check .cloud/.azure

**Comment by marvinbuss** [comment]
fixed in all repositories.
